### ISSUE TITLE
Zookeeper Events problem

### ISSUE THREAD

**Issue by toktarev** [Netflix/curator#269]
Hi I've written the following code:

package com.zk;

import org.junit.Before;
import org.junit.Test;

import com.netflix.curator.utils.ZKPaths;
import com.netflix.curator.framework.CuratorFramework;
import com.netflix.curator.framework.CuratorFrameworkFactory;
import com.netflix.curator.framework.recipes.cache.PathChildrenCache;
import com.netflix.curator.framework.recipes.cache.PathChildrenCacheEvent;
import com.netflix.curator.framework.recipes.cache.PathChildrenCacheListener;
import com.netflix.curator.retry.RetryNTimes;

import java.util.LinkedList;
import java.util.concurrent.atomic.AtomicInteger;

import static org.junit.Assert.assertEquals;

public class ZookeeperEventsTest {
    private LinkedList<Integer> data;

```
@Before
public void setUp() {

}

@Test
public void testZookeeperEvents() throws Exception {
    CuratorFramework client = CuratorFrameworkFactory.newClient("devapp090.netcracker.com:2181", new RetryNTimes(10, 1000));
    client.start();

    String znode = "/clust1/cluster/installedNodes";

    try {
        client.delete().forPath(znode + "/clust1");
    } catch (Throwable e) {

    }

    ZKPaths.mkdirs(client.getZookeeperClient().getZooKeeper(), znode, false);

    PathChildrenCache cache = new PathChildrenCache(client, znode, true);
    cache.start(true);

    final AtomicInteger i = new AtomicInteger(0);

    cache.getListenable().addListener(new PathChildrenCacheListener() {
        @Override
        public void childEvent(CuratorFramework client, PathChildrenCacheEvent event) throws Exception {
            if (event != null) {
                System.out.println("event=" + event.getType());
                i.incrementAndGet();
            }
        }
    });

    for (int j = 0; j < 25; j++) {
        client.create().forPath(znode + "/clust1", "data".getBytes());
        client.setData().forPath(znode + "/clust1", "data1".getBytes());
        client.setData().forPath(znode + "/clust1", "data2".getBytes());
        client.delete().forPath(znode + "/clust1");
    }

    Thread.sleep(5000);

    assertEquals(100, i.get());
}
```

}

Value of counter i is 68 on Average.

Is it possible that every create set delete would be caught by PathChildrenCache listener ?

Thanks.

**Comment by rfer** [comment]
If this is the case, do you recommend polling the state instead of using a listener for scenarios where you don't want to miss events? For example, detecting that nodes were removed/disappeared from the cluster.

**Comment by Randgalt** [comment]
As I mentioned above, it's not possible to get every single ZooKeeper event. PathChildrenCache will eventually give you the current state.
