### ISSUE TITLE
What's the plan for releasing changes to this?

### ISSUE THREAD

**Issue by rspieldenner** [Netflix/curator#291]
@Randgalt what's the plan for releasing this now that you moved it to a maven project?

**Comment by Randgalt** [comment]
I'm going to release it from my local machine like I do Apache Curator.

**Comment by rspieldenner** [comment]
We'd really appreciate repeatable build, pull request, and release jobs utilizing one of then many CI systems out there. If you want us to do it via Cloudbees or TravisCI I can move this back to gradle. If you want to setup your own on one of the many choices out there feel free.

If we need to make a change to this we need the ability to release it. I added the TravisCI releases so maintainers of projects outside of Netflix have the ability to release by tagging the repo.

**Comment by Randgalt** [comment]
This is a tiny project consisting of one file. The last release was 2 years ago. I don't expect many releases. The Travis build wasn't working and was starting to take far more effort than was reasonable. In 1 hour I got the build released. Much better.
