### ISSUE TITLE
InterProcessMutex from multiple threads

### ISSUE THREAD

**Issue by gmalouf** [Netflix/curator#31]
I started testing with the InterProcessMutex today and was surprised to find out that it threw an IllegalMonitorException if another thread in the same jvm already had the lock.  What I expected was behaviour within the same jvm similar to Java's standard ReentrantLock.

What are the best practices for the case where one would like the lock to be shared both within and across jvms?  What I can do short term is to try/catch the illegal monitor exception everywhere I need to call the lock but that seems cludgy and is less than ideal.  It seems like to get the behaviour I would really want the acquire method would need the ability to block.

**Comment by r7raul1984** [comment]
@Randgalt Could you show me the push url? Thanks.

**Comment by Randgalt** [comment]
Sorry @r7raul1984 - I don't know what you mean. Also, Curator is now at Apache. See https://curator.apache.org

**Comment by r7raul1984** [comment]
@Randgalt  About InterProcessMutex ,I wanted to get across was that I felt that the acquire method should block within the same jvm like it does across jvms.  How to fix it? Which version of Curator support this ?

**Comment by Randgalt** [comment]
`acquire` _does_ block in the same JVM. It acts just like the JDK lock.

**Comment by r7raul1984** [comment]
@Randgalt  OK. Thank you! I should create new CuratorFramework client for every InterProcessMutex. Many InterProcessMutex instance can't share one CuratorFramework client. Is that correct?

**Comment by Randgalt** [comment]
No - 1 CuratorFramework instance is enough for your entire application.

**Comment by r7raul1984** [comment]
@Randgalt Thanks.

**Comment by etux** [comment]
@Randgalt I am not sure if I see the behaviour expected.

I have two threads in the same JVM competing for the same lock, and both will get the lock and the last one will get an exception when releasing the lock.

So the question is: does a InterProcessMutex allow a different thread for the same JVM to acquire the mutex? is this configurable?

I am actually using curator framework 2.9.0
